theme: jekyll-theme-tactile
title: Jifeng's Blog
description: 记录所思、所做等

# Navigation
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
  About:          
    - '/about'

# tags and categories
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

# Plugins
gems:
  - jekyll-paginate

# Outputting
 permalink: /post/year/month/day/:title
paginate: 5
paginate_path: '/blog/page/:num/'
# timezone: Europe/Berlin


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag