theme: jekyll-theme-tactile
title: Jifeng's Blog
description: 记录所思、所做等

# Navigation
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
  About:
    - '/about'

# tags and categories
# https://jekyllrb.com/docs/collections/
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# markdown
markdown: kramdown
kramdown:
  input: GFM

# Outputting
# https://jekyllrb.com/docs/permalinks/
#permalink: /:categories/:year/:month/:day/:title.html
# https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page/:num/' # start with page 2
# timezone: Europe/Berlin

# plugin configuration
sitemap: true
mathjax: true # whether support mathjax

# https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
      sitemap: false
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
      sitemap: false